### PR TITLE
Documentation and building improvements

### PR DESCRIPTION
**Pull request by MGlolenstine**
- Added a build script for images.
- Added checks from #10 for better security of the scripts.
- Added a section about prebuilt  images to the `README.md`.

### CODE REVIEW

**Comment by piegamesde** [comment]
I tried `GTK=4.6.2 ADW=1.1.0 BASE=gtk4-cross-base ./build_image.sh base`:

```
FAILED: gtk/libgtk.a.p/language-names.c.obj 
/usr/bin/x86_64-w64-mingw32-gcc -Igtk/libgtk.a.p -Igtk -I../gtk -I. -I.. -Igdk -I../gdk -Igsk -I../gsk -Isubprojects/pango -I../subprojects/pango -Isubprojects/pango/pango -I../subprojects/pango/pango -Isubprojects/graphene/include -I../subprojects/graphene/include -I../gdk/x11 -Igtk/css -I/usr/x86_64-w64-mingw32/sys-root/mingw/include -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0 -I/usr/x86_64-w64-mingw32/sys-root/mingw/lib/glib-2.0/include -I/usr/x86_64-w64-mingw32/sys-root/mingw/lib/libffi-3.1/include -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/gio-win32-2.0 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/fribidi -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/harfbuzz -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/freetype2 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/libpng16 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/cairo -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/pixman-1 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/gdk-pixbuf-2.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O3 -DG_LOG_USE_STRUCTURED=1 -DGLIB_DISABLE_DEPRECATION_WARNINGS '-DGTK_VERSION="4.6.2"' -D_GNU_SOURCE -DG_DISABLE_CAST_CHECKS -DG_DISABLE_ASSERT -mstackrealign -pthread -mms-bitfields -mms-bitfields -mms-bitfields -mms-bitfields -mms-bitfields -mms-bitfields -mms-bitfields -mms-bitfields -mms-bitfields -DGTK_COMPILATION '-DG_LOG_DOMAIN="Gtk"' -DGTK_PRINT_BACKEND_ENABLE_UNSUPPORTED '-DGTK_BINARY_VERSION="4.0.0"' '-DGTK_HOST="windows"' '-DGTK_DATA_PREFIX="/usr/x86_64-w64-mingw32/sys-root/mingw"' '-DGTK_PRINT_BACKENDS="file,lpr"' -fno-strict-aliasing -Wno-missing-include-dirs -Wduplicated-branches -Wduplicated-cond -Wformat=2 -Wformat-nonliteral -Wformat-security -Wignored-qualifiers -Wimplicit-function-declaration -Wlogical-op -Wmisleading-indentation -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wshadow -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wuninitialized -Wunused -Waddress -Warray-bounds -Wempty-body -Wimplicit -Wimplicit-fallthrough -Wimplicit-fallthrough=5 -Winit-self -Wint-to-pointer-cast -Wmain -Wmissing-braces -Wmissing-declarations -Wmissing-prototypes -Wnonnull -Wpointer-to-int-cast -Wredundant-decls -Wreturn-type -Wsequence-point -Wtrigraphs -Wvla -Wwrite-strings -Wcast-align -fvisibility=hidden -MD -MQ gtk/libgtk.a.p/language-names.c.obj -MF gtk/libgtk.a.p/language-names.c.obj.d -o gtk/libgtk.a.p/language-names.c.obj -c ../gtk/language-names.c
../gtk/language-names.c: In function 'get_win32_all_locales_scripts':
../gtk/language-names.c:45:61: error: 'LOCALE_SISO639LANGNAME2' undeclared (first use in this function); did you mean 'LOCALE_SISO639LANGNAME'?
   45 |   const LCTYPE iso639_lctypes[] = { LOCALE_SISO639LANGNAME, LOCALE_SISO639LANGNAME2 };
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                             LOCALE_SISO639LANGNAME
../gtk/language-names.c:45:61: note: each undeclared identifier is reported only once for each function it appears in
../gtk/language-names.c:50:19: warning: implicit declaration of function 'GetLocaleInfoEx'; did you mean 'GetLocaleInfoA'? [-Wimplicit-function-declaration]
   50 |   langname_size = GetLocaleInfoEx (locale_w, LOCALE_SLOCALIZEDDISPLAYNAME, langname_w, 0);
      |                   ^~~~~~~~~~~~~~~
      |                   GetLocaleInfoA
../gtk/language-names.c:50:19: warning: nested extern declaration of 'GetLocaleInfoEx' [-Wnested-externs]
../gtk/language-names.c:43:46: warning: variable 'p' set but not used [-Wunused-but-set-variable]
   43 |   gchar *langname, *locale_abbrev, *locale, *p;
      |                                              ^
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/lib/glib-2.0/include/glibconfig.h:9,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0/glib/galloca.h:32,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0/glib.h:30,
                 from ../gtk/language-names.c:15:
../gtk/language-names.c: In function 'languages_init':
../gtk/language-names.c:311:21: warning: implicit declaration of function 'EnumSystemLocalesEx'; did you mean 'EnumSystemLocalesW'? [-Wimplicit-function-declaration]
  311 |   g_return_if_fail (EnumSystemLocalesEx (&get_win32_all_locales_scripts, LOCALE_ALL, (LPARAM) language_map, NULL));
      |                     ^~~~~~~~~~~~~~~~~~~
/usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0/glib/gmacros.h:1018:8: note: in definition of macro '_G_BOOLEAN_EXPR'
 1018 |    if (expr)                                    \
      |        ^~~~
/usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0/glib/gmessages.h:631:9: note: in expansion of macro 'G_LIKELY'
  631 |     if (G_LIKELY (expr)) \
      |         ^~~~~~~~
../gtk/language-names.c:311:3: note: in expansion of macro 'g_return_if_fail'
  311 |   g_return_if_fail (EnumSystemLocalesEx (&get_win32_all_locales_scripts, LOCALE_ALL, (LPARAM) language_map, NULL));
      |   ^~~~~~~~~~~~~~~~
../gtk/language-names.c:311:21: warning: nested extern declaration of 'EnumSystemLocalesEx' [-Wnested-externs]
  311 |   g_return_if_fail (EnumSystemLocalesEx (&get_win32_all_locales_scripts, LOCALE_ALL, (LPARAM) language_map, NULL));
      |                     ^~~~~~~~~~~~~~~~~~~
/usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0/glib/gmacros.h:1018:8: note: in definition of macro '_G_BOOLEAN_EXPR'
 1018 |    if (expr)                                    \
      |        ^~~~
/usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0/glib/gmessages.h:631:9: note: in expansion of macro 'G_LIKELY'
  631 |     if (G_LIKELY (expr)) \
      |         ^~~~~~~~
../gtk/language-names.c:311:3: note: in expansion of macro 'g_return_if_fail'
  311 |   g_return_if_fail (EnumSystemLocalesEx (&get_win32_all_locales_scripts, LOCALE_ALL, (LPARAM) language_map, NULL));
      |   ^~~~~~~~~~~~~~~~
../gtk/language-names.c:311:74: error: 'LOCALE_ALL' undeclared (first use in this function); did you mean 'LOCALE_SDATE'?
  311 |   g_return_if_fail (EnumSystemLocalesEx (&get_win32_all_locales_scripts, LOCALE_ALL, (LPARAM) language_map, NULL));
      |                                                                          ^~~~~~~~~~
/usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0/glib/gmacros.h:1018:8: note: in definition of macro '_G_BOOLEAN_EXPR'
 1018 |    if (expr)                                    \
      |        ^~~~
/usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0/glib/gmessages.h:631:9: note: in expansion of macro 'G_LIKELY'
  631 |     if (G_LIKELY (expr)) \
      |         ^~~~~~~~
../gtk/language-names.c:311:3: note: in expansion of macro 'g_return_if_fail'
  311 |   g_return_if_fail (EnumSystemLocalesEx (&get_win32_all_locales_scripts, LOCALE_ALL, (LPARAM) language_map, NULL));
      |   ^~~~~~~~~~~~~~~~
[1072/1716] Compiling C object demos/gtk-demo/gtk4-demo.exe.p/gtkfishbowl.c.obj
[1073/1716] Compiling C object demos/gtk-demo/gtk4-demo.exe.p/fontplane.c.obj
[1074/1716] Compiling C object demos/gtk-demo/gtk4-demo.exe.p/gtkshaderbin.c.obj
[1075/1716] Compiling C object demos/gtk-demo/gtk4-demo.exe.p/main.c.obj
[1076/1716] Compiling C object demos/gtk-demo/gtk4-demo.exe.p/gtkshaderstack.c.obj
[1077/1716] Compiling C object demos/gtk-demo/gtk4-demo.exe.p/gtkgears.c.obj
[1078/1716] Compiling C object demos/gtk-demo/gtk4-demo.exe.p/gtkshadertoy.c.obj
[1079/1716] Compiling C object demos/gtk-demo/gtk4-demo.exe.p/gskshaderpaintable.c.obj
[1080/1716] Compiling C object demos/gtk-demo/gtk4-demo.exe.p/bluroverlay.c.obj
ninja: build stopped: subcommand failed.
Error: error building at STEP "RUN ninja all && ninja install": error while running runtime: exit status 1
```

**Comment by MGlolenstine** [comment]
I do think that that's some issue with GTK, as it fails at its compilation.
I just tested it out with `GTK=4.6.0 ADW=1.0.1` which I know are compatible (I will double check to see if there's some problems with dependencies for newer versions as well).
```
[notyours@notyours gtk4-cross]$ GTK=4.6.0 ADW=1.0.1 ./build_image.sh base
<...>
Successfully tagged localhost/gtk4-cross-base-hub-4.6.0-1.0.1:latest
c8ceae2e277b0aca1d4f6b6cc93ca7b27c61f9e2e37419ab15d5973f3967b723
```

`BASE` does nothing when compiling the base image. `BASE` is the base image name used for building crates that depend on the base image (`rust` in this example)

**Comment by piegamesde** [comment]
Thank you, it mostly works now. If not all versions build successfully, maybe documenting known good values could be a good idea?

As before, I had to comment out `RUN curl https://sh.rustup.rs -sSf | sh -s -- -y` from `gtk4-cross-rust/Dockerfile`, otherwise I would get "error: could not rename component file from '/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/self-contained' to '/root/.rustup/tmp/w3rjds46kdxu8xlj_dir/bk': Invalid cross-device link (os error 18)"

My application compiles fine now, but I still get the weird linker error at the end where it can't find a lot of libraries.

**Comment by MGlolenstine** [comment]
Currently the only version I couldn't get to build is `GTK=4.6.2`. All versions up to it work fine.
As for the building of `rust` image, I get no such errors...
```
[notyours@notyours gtk4-cross]$ GTK=4.6.0 ADW=1.0.1 BASE="gtk4-cross-base-hub-4.6.0-1.0.1"  ./build_image.sh rust
<...>
STEP 12/14: RUN . ~/.cargo/env &&     rustup target add x86_64-pc-windows-gnu
info: downloading component 'rust-std' for 'x86_64-pc-windows-gnu'
info: installing component 'rust-std' for 'x86_64-pc-windows-gnu'
--> 698869feb1a
STEP 13/14: ADD cargo.config /home/rust/.cargo/config
--> 253a36254fc
STEP 14/14: CMD ["/bin/bash"]
COMMIT gtk4-cross-rust-4.6.0-1.0.1
--> 8ed4ff23f44
Successfully tagged localhost/gtk4-cross-rust-4.6.0-1.0.1:latest
8ed4ff23f44b73767ac5a6e5a08996048b361ffebd10b4bfb54bcfe20813cd22
```
Could I get more information about the missing libraries?
Could you create a minimal reproducible example for me to test on?

**Comment by piegamesde** [comment]
> As before, I had to comment out RUN curl https://sh.rustup.rs -sSf | sh -s -- -y from gtk4-cross-rust/Dockerfile

My bad, I was using an older cached image.

About the linker error, this isn't totally obvious from the output, but I suspect that it is not the crate that fails, but the custom build script

```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.0.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.1.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.10.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.11.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.12.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.13.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.14.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.15.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.2.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.3.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.4.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.5.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.6.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.7.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.8.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.build_script_build.4e57be0f-cgu.9.rcgu.o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3.1myfwb6h4vkc21nr.rcgu.o" "-Wl,--as-needed" "-L" "/mnt/target/release/deps" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/usr/x86_64-w64-mingw32/sys-root/mingw/lib" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/mnt/target/release/deps/libgtk4-34c59c32d75c5e0a.rlib" "/mnt/target/release/deps/libgsk4-26cf86c832031250.rlib" "/mnt/target/release/deps/libgraphene-00213d4cd5602640.rlib" "/mnt/target/release/deps/libgdk4-1c7f4a2dafba1aee.rlib" "/mnt/target/release/deps/libpango-2ef1c09aaeb7a84b.rlib" "/mnt/target/release/deps/libgdk_pixbuf-4b662b4d7c46c319.rlib" "/mnt/target/release/deps/libgio-9ab201c0a13ef5d7.rlib" "/mnt/target/release/deps/libfutures_io-b2bd3bc4c5bd9372.rlib" "/mnt/target/release/deps/libcairo-1eb74cfaa9b1ccbc.rlib" "/mnt/target/release/deps/libglib-0f136eec3282be03.rlib" "/mnt/target/release/deps/libfutures_executor-5702273294728f95.rlib" "/mnt/target/release/deps/libfutures_util-254680171981260d.rlib" "/mnt/target/release/deps/libslab-e6b7f9d6041ef0cd.rlib" "/mnt/target/release/deps/libpin_project_lite-1542fd4f5f4b99bd.rlib" "/mnt/target/release/deps/libpin_utils-e37413679ecf9271.rlib" "/mnt/target/release/deps/libsmallvec-7fa6549f765b4b40.rlib" "/mnt/target/release/deps/libthiserror-629f3c5301df5d92.rlib" "/mnt/target/release/deps/libfutures_channel-f807eea6f445723b.rlib" "/mnt/target/release/deps/libfutures_task-0784dee246216af7.rlib" "/mnt/target/release/deps/libfutures_core-5042d123a4bb11f1.rlib" "/mnt/target/release/deps/libonce_cell-ff4c8cc7d8bea291.rlib" "/mnt/target/release/deps/libbitflags-5f7dc55c5a4a85d3.rlib" "/mnt/target/release/deps/libgtk4_sys-26359e817cec7fad.rlib" "/mnt/target/release/deps/libgsk4_sys-c08a0762cd7957b9.rlib" "/mnt/target/release/deps/libgraphene_sys-80b4480c9044f33c.rlib" "/mnt/target/release/deps/libgdk4_sys-1d19fecb7ea2e4aa.rlib" "/mnt/target/release/deps/libgdk_pixbuf_sys-4ee956fc464c3c22.rlib" "/mnt/target/release/deps/libpango_sys-067b85ef70f5e14a.rlib" "/mnt/target/release/deps/libcairo_sys-7b1e0305a1a0f095.rlib" "/mnt/target/release/deps/libgio_sys-c618da8480af9e86.rlib" "/mnt/target/release/deps/libgobject_sys-0472a3fc8f4a4c9a.rlib" "/mnt/target/release/deps/libglib_sys-f13b39043cdadac7.rlib" "/mnt/target/release/deps/liblibc-5b05a08a12f1535d.rlib" "/mnt/target/release/deps/libfield_offset-ebf518d1a2f0b69f.rlib" "/mnt/target/release/deps/libmemoffset-eb6a7c831bdc4e1c.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-8d61b92a0a02f53a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-fc45202bb435016b.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-f2400674c7513725.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-605c3a7d1a5d300d.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-3d4fb4efa907e4e8.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-65207f030ab23308.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-76ca199cb0186109.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-1e3e01ed4f561dc1.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-dd8dddcba7c13fee.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-00b13d31c3420656.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-e4c8460b81557bd5.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-600d46e5f0005455.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-e4a08a2585b62d37.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-fbc21ec567cb9dc7.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-10b3fa8e49bd978f.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-64625b73694ffce7.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-fb6b78ac543a58ee.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-1d1f2d1bec6f51b8.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-acf5ff6e9595d982.rlib" "-Wl,-Bdynamic" "-lgobject-2.0" "-lgtk-4" "-lpangowin32-1.0" "-lpangocairo-1.0" "-lpango-1.0" "-lharfbuzz" "-lgdk_pixbuf-2.0" "-lcairo-gobject" "-lcairo" "-lgraphene-1.0" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgtk-4" "-lpangowin32-1.0" "-lpangocairo-1.0" "-lpango-1.0" "-lharfbuzz" "-lgdk_pixbuf-2.0" "-lcairo-gobject" "-lcairo" "-lgraphene-1.0" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgraphene-1.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgtk-4" "-lpangowin32-1.0" "-lpangocairo-1.0" "-lpango-1.0" "-lharfbuzz" "-lgdk_pixbuf-2.0" "-lcairo-gobject" "-lcairo" "-lgraphene-1.0" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgdk_pixbuf-2.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lpango-1.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lharfbuzz" "-lcairo-gobject" "-lcairo" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/mnt/target/release/build/dinoscore-cf015bae71e00ef3/build_script_build-cf015bae71e00ef3" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lgtk-4
          /usr/bin/ld: cannot find -lpangowin32-1.0
          /usr/bin/ld: cannot find -lpangocairo-1.0
          /usr/bin/ld: cannot find -lpango-1.0
          /usr/bin/ld: cannot find -lharfbuzz
          /usr/bin/ld: cannot find -lgdk_pixbuf-2.0
          /usr/bin/ld: cannot find -lcairo-gobject
          /usr/bin/ld: cannot find -lcairo
          /usr/bin/ld: cannot find -lgraphene-1.0
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lgtk-4
          /usr/bin/ld: cannot find -lpangowin32-1.0
          /usr/bin/ld: cannot find -lpangocairo-1.0
          /usr/bin/ld: cannot find -lpango-1.0
          /usr/bin/ld: cannot find -lharfbuzz
          /usr/bin/ld: cannot find -lgdk_pixbuf-2.0
          /usr/bin/ld: cannot find -lcairo-gobject
          /usr/bin/ld: cannot find -lcairo
          /usr/bin/ld: cannot find -lgraphene-1.0
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lgraphene-1.0
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lgtk-4
          /usr/bin/ld: cannot find -lpangowin32-1.0
          /usr/bin/ld: cannot find -lpangocairo-1.0
          /usr/bin/ld: cannot find -lpango-1.0
          /usr/bin/ld: cannot find -lharfbuzz
          /usr/bin/ld: cannot find -lgdk_pixbuf-2.0
          /usr/bin/ld: cannot find -lcairo-gobject
          /usr/bin/ld: cannot find -lcairo
          /usr/bin/ld: cannot find -lgraphene-1.0
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lgdk_pixbuf-2.0
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lpango-1.0
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lharfbuzz
          /usr/bin/ld: cannot find -lcairo-gobject
          /usr/bin/ld: cannot find -lcairo
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lintl
          collect2: error: ld returned 1 exit status
```

**Comment by MGlolenstine** [comment]
I'm guessing that `dinoscore` is a private crate...

Could you create a minimal reproducible example?
I'd love to debug, but I'll have to add and test all those dependencies manually.
The current `rust` image does build my application correctly, so I do think that your guess about it being caused by a custom build script is correct.

If it's possible to share the crate (either privately or here), I'd love to take a look.

**Comment by piegamesde** [comment]
The code is available at https://github.com/DiNoScore/DiNoScore/tree/gtk4, feel free to try it out if you want to. Otherwise, I'll try to minimize later this week.

(Note that you need to add `RUN dnf install mingw64-poppler mingw64-poppler-glib -y && dnf clean all -y` for additional dependencies of the project)

**Comment by MGlolenstine** [comment]
I can try building the whole project, I just wanted to have something that reproduced the issue.

> One thing that I noticed though is the ADD cargo.config /home/rust/.cargo/config line in the docker file.

IIRC, that was there because rust used a different home platform for it's own configuration, but I'm probably wrong... (I must've had a reason for adding it in :thinking:)

**Comment by MGlolenstine** [comment]
I've tested building `DiNoScore` and I've been unable to complete a build, got the same error as you did.
I'm not sure how the Rust compilation works in this case, but it seems to be using Linux libraries even when building for Windows.

By installing the following packages 
> RUN dnf install rust-cairo-sys-rs-devel graphene-devel cairo-gobject-devel rust-pangocairo-sys-devel rust-gdk-pixbuf-sys-devel rust-pango-devel gtk4-devel -y && dnf clean all -y
I've been able to change the error down to 
```
  = note: /usr/bin/ld: cannot find -lpangowin32-1.0
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lpangowin32-1.0
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lpangowin32-1.0
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lintl
          /usr/bin/ld: cannot find -lintl
          collect2: error: ld returned 1 exit status
```
I'm unsure on how to get the last two dependencies sorted out, as I have no idea where to get them.

I don't think this is the issue with the docker image though, but with the build script, like you noted before.

**Comment by piegamesde** [comment]
Thanks for having a look. I commented out the build script and ran into a few more errors, but nothing related with this PR. The changes are fine.

**Comment by MGlolenstine** [comment]
Thank you for testing out the PR!

**Pull request merged**
