### PR TITLE
Improve packaging script

### PR DESCRIPTION
**Pull request by piegamesde**
I think my packaging script is sufficiently "done" so that I can upstream it. Also, since packaging is not specific to Rust, I moved it to the base image. This is a compatibility breaking change because I do not zip the result anymore.

### CODE REVIEW

**Comment by MGlolenstine** [comment]
LGTM.
Removal of zip operation seems fine to me, as people can always just add `package.sh` and zip it afterwards using the following:
```bash
#!/bin/bash
package
zip -r package.zip package
```
and running `./package.sh` instead of `package` directly.

**Review by MGlolenstine — CHANGES_REQUESTED** [review]
These and the removal of `package_with_icons.sh` fail your builds.
https://github.com/piegamesde/gtk4-cross/runs/6951072370?check_suite_focus=true#step:9:67
(Although I'm not sure how it passes on the outside)

**Comment by piegamesde** [comment]
Thanks for the notice. I also changed the CI so that it fails on failure, otherwise I would have completely missed it.

**Review by MGlolenstine — APPROVED** [review]

**Comment by MGlolenstine** [comment]
LGTM, thanks for the contribution!

**Pull request merged**
